### ISSUE TITLE
Add PostgreSQL support to the bot stack

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#30]
**DB Tables:**
`queue`: messages received by the bot are placed in this table for further processing at the specified time by a separate thread
- id (int)
- user id (int)
- post url (str)
- post id (str)
- scheduled_time (datetime)
- timestamp (datetime)
- post owner (str)
- message id (str)
- chat id (str)
- link type (post or profile) (str)
- state (str)

`processed`: historical data from vault should be migrated here and after processing from `queue`, the record should be moved to this table, enriched with additional data
- id (int)
- queue id (str)
- user id (str)
- post url (str)
- post id (str)
- timestamp (datetime)
- download status (str)
- upload status (str)
- post owner (str)

`migrations`: table for service migrations (for example, transferring historical data from vault)
- id (str)
- name (str)
- version (str)
- completion time (datetime)

`locks`: this table will record the locks caused by various exceptions when the bot is running. First of all, for a rotten session (401). These locks will block various bot functionality until manual intervention.
- id (str)
- name (str)
- behaviour (str)
- timestamp (datetime)
- enabled (bool)
- description (str)
- caused by (str)

**To-Do:**
- [x] Write migration of historical data from vault to postgresql
    - [x] migration should leave a mark in the migrations table after completion
    - [x] the migration shouldn’t delete the migrated data in the vault
- [x] The bot should automatically create tables in the database at startup
- [x] The configuration of the database connection must be stored and read by the vault
- [x] To work with a database, you need to create a separate class with a set of methods and attributes for interacting with tables
