### ISSUE TITLE
Feature request: Add a bash script to configure vault and postgresql to the repository

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#66]
**Is your feature request related to a problem? Please describe.**
Add simple scripts to configure dependency services: Vault and Postgresql.
To simplify project deployment and documentation of service dependencies

**Describe the solution you'd like**
A simple bash script with step-by-step echo and using `vault` and `psql` console clients.

**Describe alternatives you've considered**
None

**Additional context**
None

**To-Do list**
- [ ] remove the obsolete way of preparing vault via python module
- [ ] in the documentation leave only the example with script calls and a link to them, remove the step-by-step console commands (this will be transparently visible in the bash-script itself)
- [ ] write two simple bash scripts `prepare_vault.sh` and `prepare_pgsql.sh`
